
package com.m104.futebol.model.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimesWS", targetNamespace = "http://webservice.model.futebol.m104.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimesWS {


    /**
     * 
     * @return
     *     returns java.util.List<com.m104.futebol.model.webservice.Time>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarTodos", targetNamespace = "http://webservice.model.futebol.m104.com/", className = "com.m104.futebol.model.webservice.BuscarTodos")
    @ResponseWrapper(localName = "buscarTodosResponse", targetNamespace = "http://webservice.model.futebol.m104.com/", className = "com.m104.futebol.model.webservice.BuscarTodosResponse")
    public List<Time> buscarTodos();

    /**
     * 
     * @return
     *     returns java.util.List<com.m104.futebol.model.webservice.Jogador>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarTodosJogadores", targetNamespace = "http://webservice.model.futebol.m104.com/", className = "com.m104.futebol.model.webservice.BuscarTodosJogadores")
    @ResponseWrapper(localName = "buscarTodosJogadoresResponse", targetNamespace = "http://webservice.model.futebol.m104.com/", className = "com.m104.futebol.model.webservice.BuscarTodosJogadoresResponse")
    public List<Jogador> buscarTodosJogadores();

}
