
package com.m104.futebol.model.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TimesWSService", targetNamespace = "http://webservice.model.futebol.m104.com/", wsdlLocation = "http://localhost:8085/futebol/TimesWS?wsdl")
public class TimesWSService
    extends Service
{

    private final static URL TIMESWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException TIMESWSSERVICE_EXCEPTION;
    private final static QName TIMESWSSERVICE_QNAME = new QName("http://webservice.model.futebol.m104.com/", "TimesWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/futebol/TimesWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TIMESWSSERVICE_WSDL_LOCATION = url;
        TIMESWSSERVICE_EXCEPTION = e;
    }

    public TimesWSService() {
        super(__getWsdlLocation(), TIMESWSSERVICE_QNAME);
    }

    public TimesWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIMESWSSERVICE_QNAME, features);
    }

    public TimesWSService(URL wsdlLocation) {
        super(wsdlLocation, TIMESWSSERVICE_QNAME);
    }

    public TimesWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIMESWSSERVICE_QNAME, features);
    }

    public TimesWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TimesWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TimesWS
     */
    @WebEndpoint(name = "TimesWSPort")
    public TimesWS getTimesWSPort() {
        return super.getPort(new QName("http://webservice.model.futebol.m104.com/", "TimesWSPort"), TimesWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimesWS
     */
    @WebEndpoint(name = "TimesWSPort")
    public TimesWS getTimesWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.model.futebol.m104.com/", "TimesWSPort"), TimesWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIMESWSSERVICE_EXCEPTION!= null) {
            throw TIMESWSSERVICE_EXCEPTION;
        }
        return TIMESWSSERVICE_WSDL_LOCATION;
    }

}
